### ISSUE TITLE
CToA calculation

### ISSUE THREAD

**Issue by leon-vv** [M4I-nanoscopy/tpx3HitParser#3]
![image](https://user-images.githubusercontent.com/4085287/95448500-b9e2e880-0963-11eb-81b6-1fd32a019b77.png)

Hi there, I'm working for ASI to develop a data analysis tool for the Tpx3 raw data format. I could not get my toa calculations to agree with yours. Shouldn't this be `CToA = (ToA << 4) - fToA` ?

**Comment by PaulVanSchayck** [comment]
Let me double check a few things and get back to you.

**Comment by PaulVanSchayck** [comment]
Hi Leon,

I did another check of this. The two are equivalent. Mine is the addition of the inverse, which is the same as substracting.

I was looking at this code again as part of an effort to speed up the whole thing. I've refactored these bits a bit to combine the SPIDR time, the coarse and fine ToA into one counter. But also look for SPIDR rollovers, and add this to the timer. So you can count beyond 26 seconds. You can see this here:

https://github.com/M4I-nanoscopy/tpx3HitParser/blob/refactor_speed/tpx3format/read.py

**Comment by leon-vv** [comment]
![image](https://user-images.githubusercontent.com/4085287/107961653-7dc13380-6fa6-11eb-8352-27c5905aeada.png)

I still don't really see how they are equivalent.


Looks good! I also had to implement something similar when reading Tpx3 data. It looks like the algorithms we ended up with (which has to account for the unsorted data) is very similar.

**Comment by PaulVanSchayck** [comment]
You're right:

```
coarse_toa << 4, coarse_toa << 4) | (~fine_toa & 0xf), int(coarse_toa << 4) - int(fine_toa)
89312, 89298, 89313
86288, 86273, 86288
90288, 90282, 90297
89120, 89110, 89125
90304, 90296, 90311
91008, 90995, 91010
90288, 90283, 90298
89728, 89727, 89742
89744, 89729, 89744
89120, 89111, 89126
90816, 90811, 90826
88352, 88347, 88362
```
There is a consistent 15 value difference between your and my solution. But I think your solution is correct, because the fine_toa is counting backwards from the ToA. Should it should subtract from the coarse_toa, not add.
